### ISSUE TITLE
Add instructions for getting started to README

### ISSUE THREAD

**Issue by sbeitzel** [FourThievesVinegar/vinni#19]
Simply running `git clone git@github.com:FourThievesVinegar/vinni.git` and then `cd vinni && yarn start` won't work, because the required frameworks aren't included in the repo:

```
% yarn start
yarn run v1.22.15
$ react-scripts start
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

First, one must tell yarn to go fetch all the dependencies. For someone used to working with yarn, this may be implicit, but it should probably explicitly called out in the README.

**Comment by sparklestheunicorn** [comment]
`yarn install` was added to the docs in [PR 20](https://github.com/FourThievesVinegar/vinni/pull/20), which should address this issue.
